/**
 * Complete registry of all 23 Austrian laws:
 * - 9 Gemeindeordnungen (one per Bundesland, Wien uses Wiener Stadtverfassung)
 * - 14 Statutarstadt-Stadtrechte
 *
 * Each entry uses verified GeltendeFassung.wxe URLs from RIS.
 * Composite key: abfrage + gesetzesnummer (gesetzesnummer alone is NOT unique).
 */

const RIS_BASE = 'https://www.ris.bka.gv.at/GeltendeFassung.wxe';

function risUrl(abfrage, gesetzesnummer) {
  return `${RIS_BASE}?Abfrage=${abfrage}&Gesetzesnummer=${gesetzesnummer}`;
}

export const LAWS = {
  gemeindeordnungen: {
    burgenland: {
      name: 'Bgld. Gemeindeordnung 2003',
      abfrage: 'LrBgld',
      gesetzesnummer: '20000221',
      url: risUrl('LrBgld', '20000221'),
      category: 'gemeindeordnung',
      stadt: null,
      bundesland: 'Burgenland',
    },
    kaernten: {
      name: 'Kaerntner Allgemeine Gemeindeordnung (K-AGO)',
      abfrage: 'LrK',
      gesetzesnummer: '10000276',
      url: risUrl('LrK', '10000276'),
      category: 'gemeindeordnung',
      stadt: null,
      bundesland: 'Kaernten',
    },
    niederoesterreich: {
      name: 'NOe. Gemeindeordnung 1973',
      abfrage: 'LrNO',
      gesetzesnummer: '20000105',
      url: risUrl('LrNO', '20000105'),
      category: 'gemeindeordnung',
      stadt: null,
      bundesland: 'Niederoesterreich',
    },
    oberoesterreich: {
      name: 'OOe. Gemeindeordnung 1990',
      abfrage: 'LrOO',
      gesetzesnummer: '10000288',
      url: risUrl('LrOO', '10000288'),
      category: 'gemeindeordnung',
      stadt: null,
      bundesland: 'Oberoesterreich',
    },
    salzburg: {
      name: 'Salzburger Gemeindeordnung 2019',
      abfrage: 'LrSbg',
      gesetzesnummer: '20001240',
      url: risUrl('LrSbg', '20001240'),
      category: 'gemeindeordnung',
      stadt: null,
      bundesland: 'Salzburg',
    },
    steiermark: {
      name: 'Steierm. Gemeindeordnung 1967',
      abfrage: 'LrStmk',
      gesetzesnummer: '20000218',
      url: risUrl('LrStmk', '20000218'),
      category: 'gemeindeordnung',
      stadt: null,
      bundesland: 'Steiermark',
    },
    tirol: {
      name: 'Tiroler Gemeindeordnung 2001',
      abfrage: 'LrT',
      gesetzesnummer: '20000101',
      url: risUrl('LrT', '20000101'),
      category: 'gemeindeordnung',
      stadt: null,
      bundesland: 'Tirol',
    },
    vorarlberg: {
      name: 'Vorarlberger Gemeindegesetz',
      abfrage: 'LrVbg',
      gesetzesnummer: '20000047',
      url: risUrl('LrVbg', '20000047'),
      category: 'gemeindeordnung',
      stadt: null,
      bundesland: 'Vorarlberg',
    },
    wien: {
      name: 'Wiener Stadtverfassung',
      abfrage: 'LrW',
      gesetzesnummer: '20000308',
      url: risUrl('LrW', '20000308'),
      category: 'gemeindeordnung',
      stadt: null,
      bundesland: 'Wien',
    },
  },

  stadtrechte: {
    eisenstadt: {
      name: 'Eisenstaedter Stadtrecht 2003',
      abfrage: 'LrBgld',
      gesetzesnummer: '20000222',
      url: risUrl('LrBgld', '20000222'),
      category: 'stadtrecht',
      stadt: 'Eisenstadt',
      bundesland: 'Burgenland',
    },
    rust: {
      name: 'Ruster Stadtrecht 2003',
      abfrage: 'LrBgld',
      gesetzesnummer: '20000224',
      url: risUrl('LrBgld', '20000224'),
      category: 'stadtrecht',
      stadt: 'Rust',
      bundesland: 'Burgenland',
    },
    klagenfurt: {
      name: 'Klagenfurter Stadtrecht 1998 (K-KStR)',
      abfrage: 'LrK',
      gesetzesnummer: '10000279',
      url: risUrl('LrK', '10000279'),
      category: 'stadtrecht',
      stadt: 'Klagenfurt',
      bundesland: 'Kaernten',
    },
    villach: {
      name: 'Villacher Stadtrecht 1998 (K-VStR)',
      abfrage: 'LrK',
      gesetzesnummer: '10000278',
      url: risUrl('LrK', '10000278'),
      category: 'stadtrecht',
      stadt: 'Villach',
      bundesland: 'Kaernten',
    },
    krems: {
      name: 'Kremser Stadtrecht 1977',
      abfrage: 'LrNO',
      gesetzesnummer: '20000064',
      url: risUrl('LrNO', '20000064'),
      category: 'stadtrecht',
      stadt: 'Krems',
      bundesland: 'Niederoesterreich',
    },
    st_poelten: {
      name: 'St. Poeltner Stadtrecht 1977',
      abfrage: 'LrNO',
      gesetzesnummer: '20000101',
      url: risUrl('LrNO', '20000101'),
      category: 'stadtrecht',
      stadt: 'St. Poelten',
      bundesland: 'Niederoesterreich',
    },
    waidhofen: {
      name: 'Waidhofner Stadtrecht 1977',
      abfrage: 'LrNO',
      gesetzesnummer: '20000100',
      url: risUrl('LrNO', '20000100'),
      category: 'stadtrecht',
      stadt: 'Waidhofen/Ybbs',
      bundesland: 'Niederoesterreich',
    },
    wr_neustadt: {
      name: 'Wr. Neustaedter Stadtrecht 1977',
      abfrage: 'LrNO',
      gesetzesnummer: '20000066',
      url: risUrl('LrNO', '20000066'),
      category: 'stadtrecht',
      stadt: 'Wr. Neustadt',
      bundesland: 'Niederoesterreich',
    },
    linz: {
      name: 'Statut fuer die Landeshauptstadt Linz 1992',
      abfrage: 'LrOO',
      gesetzesnummer: '10000341',
      url: risUrl('LrOO', '10000341'),
      category: 'stadtrecht',
      stadt: 'Linz',
      bundesland: 'Oberoesterreich',
    },
    steyr: {
      name: 'Statut fuer die Stadt Steyr 1992',
      abfrage: 'LrOO',
      gesetzesnummer: '10000342',
      url: risUrl('LrOO', '10000342'),
      category: 'stadtrecht',
      stadt: 'Steyr',
      bundesland: 'Oberoesterreich',
    },
    wels: {
      name: 'Statut fuer die Stadt Wels 1992',
      abfrage: 'LrOO',
      gesetzesnummer: '10000345',
      url: risUrl('LrOO', '10000345'),
      category: 'stadtrecht',
      stadt: 'Wels',
      bundesland: 'Oberoesterreich',
    },
    salzburg_stadt: {
      name: 'Salzburger Stadtrecht 1966',
      abfrage: 'LrSbg',
      gesetzesnummer: '10000140',
      url: risUrl('LrSbg', '10000140'),
      category: 'stadtrecht',
      stadt: 'Salzburg',
      bundesland: 'Salzburg',
    },
    graz: {
      name: 'Statut der Landeshauptstadt Graz 1967',
      abfrage: 'LrStmk',
      gesetzesnummer: '20000217',
      url: risUrl('LrStmk', '20000217'),
      category: 'stadtrecht',
      stadt: 'Graz',
      bundesland: 'Steiermark',
    },
    innsbruck: {
      name: 'Innsbrucker Stadtrecht 1975',
      abfrage: 'LrT',
      gesetzesnummer: '20000196',
      url: risUrl('LrT', '20000196'),
      category: 'stadtrecht',
      stadt: 'Innsbruck',
      bundesland: 'Tirol',
    },
  },
};
